export const DEFAULT_TABS = [
  { label: 'dir', id: 'terminal-1' },
  { label: 'node -v', id: 'terminal-2' },
  { label: 'code .', id: 'terminal-3' },
  { label: 'help', id: 'terminal-4' },
  { label: 'systeminfo', id: 'terminal-5' },
  { label: 'yo', id: 'terminal-6' },
  { label: 'npm install', id: 'terminal-7' },
  { label: 'npm update', id: 'terminal-8' },
  { label: 'git status', id: 'terminal-9' },
  { label: 'git pull', id: 'terminal-10' },
  { label: 'git push', id: 'terminal-11' },
  { label: 'npm run build', id: 'terminal-12' },
  { label: 'npm start', id: 'terminal-13' },
  { label: 'npm run test', id: 'terminal-14' },
  { label: 'npx create-react-app my-app', id: 'terminal-15' },
  { label: 'python --version', id: 'terminal-16' },
  { label: 'pip install package_name', id: 'terminal-17' },
  { label: 'explorer .', id: 'terminal-18' },
  { label: 'cls', id: 'terminal-19' },
  { label: 'clear', id: 'terminal-20' },
  { label: 'echo Hello World', id: 'terminal-21' }
];